# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/hgfs/Code/git_code/httpry

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/hgfs/Code/git_code/httpry

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/hgfs/Code/git_code/httpry/CMakeFiles /mnt/hgfs/Code/git_code/httpry/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/hgfs/Code/git_code/httpry/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named httpry

# Build rule for target.
httpry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpry
.PHONY : httpry

# fast build rule for target.
httpry/fast:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/build
.PHONY : httpry/fast

src/format.o: src/format.c.o
.PHONY : src/format.o

# target to build an object file
src/format.c.o:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/format.c.o
.PHONY : src/format.c.o

src/format.i: src/format.c.i
.PHONY : src/format.i

# target to preprocess a source file
src/format.c.i:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/format.c.i
.PHONY : src/format.c.i

src/format.s: src/format.c.s
.PHONY : src/format.s

# target to generate assembly for a file
src/format.c.s:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/format.c.s
.PHONY : src/format.c.s

src/httpry.o: src/httpry.c.o
.PHONY : src/httpry.o

# target to build an object file
src/httpry.c.o:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/httpry.c.o
.PHONY : src/httpry.c.o

src/httpry.i: src/httpry.c.i
.PHONY : src/httpry.i

# target to preprocess a source file
src/httpry.c.i:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/httpry.c.i
.PHONY : src/httpry.c.i

src/httpry.s: src/httpry.c.s
.PHONY : src/httpry.s

# target to generate assembly for a file
src/httpry.c.s:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/httpry.c.s
.PHONY : src/httpry.c.s

src/methods.o: src/methods.c.o
.PHONY : src/methods.o

# target to build an object file
src/methods.c.o:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/methods.c.o
.PHONY : src/methods.c.o

src/methods.i: src/methods.c.i
.PHONY : src/methods.i

# target to preprocess a source file
src/methods.c.i:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/methods.c.i
.PHONY : src/methods.c.i

src/methods.s: src/methods.c.s
.PHONY : src/methods.s

# target to generate assembly for a file
src/methods.c.s:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/methods.c.s
.PHONY : src/methods.c.s

src/rate.o: src/rate.c.o
.PHONY : src/rate.o

# target to build an object file
src/rate.c.o:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/rate.c.o
.PHONY : src/rate.c.o

src/rate.i: src/rate.c.i
.PHONY : src/rate.i

# target to preprocess a source file
src/rate.c.i:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/rate.c.i
.PHONY : src/rate.c.i

src/rate.s: src/rate.c.s
.PHONY : src/rate.s

# target to generate assembly for a file
src/rate.c.s:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/rate.c.s
.PHONY : src/rate.c.s

src/utility.o: src/utility.c.o
.PHONY : src/utility.o

# target to build an object file
src/utility.c.o:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/utility.c.o
.PHONY : src/utility.c.o

src/utility.i: src/utility.c.i
.PHONY : src/utility.i

# target to preprocess a source file
src/utility.c.i:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/utility.c.i
.PHONY : src/utility.c.i

src/utility.s: src/utility.c.s
.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.c.s:
	$(MAKE) -f CMakeFiles/httpry.dir/build.make CMakeFiles/httpry.dir/src/utility.c.s
.PHONY : src/utility.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... httpry"
	@echo "... rebuild_cache"
	@echo "... src/format.o"
	@echo "... src/format.i"
	@echo "... src/format.s"
	@echo "... src/httpry.o"
	@echo "... src/httpry.i"
	@echo "... src/httpry.s"
	@echo "... src/methods.o"
	@echo "... src/methods.i"
	@echo "... src/methods.s"
	@echo "... src/rate.o"
	@echo "... src/rate.i"
	@echo "... src/rate.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

